config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  devise_for :users, :controllers => { registrations: 'registrations' , sessions: 'sessions' }
  root 'users#index'
  get '/users' => 'users#home', as: 'users'
  get '/users/:id' => 'users#show', as: 'user'
  get '/map' => 'jobs#map', as: 'job_map'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
    belongs_to :user
    # :acceptor = what rails console will refer to e.g. Job.acceptor
    # :foreign_key => 'acceptor_id' = the column in jobs table
    # :class-name => 'User' = using the above integer of 'acceptor_id' column, used as id to call the row in 'User' table
    belongs_to :acceptor, :foreign_key => 'acceptor_id', :class_name => 'User', :optional => true
    # validates :acceptor_id, presence: false
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user_id = current_user.id
        @job.acceptor_id = nil
        if @job.package_picture == nil
          p 'profile pic is nil'
          @job.package_picture = 'https://media.istockphoto.com/vectors/box-icon-flat-design-style-parcel-simple-silhouette-modern-minimalist-vector-id1033754126?k=6&m=1033754126&s=612x612&w=0&h=X4dkpNwkjkh568SQ8FvFUo7aKEZT-kdxPUBcYTeUZRA='
        else
          p 'profile pic is not nil'
          uploaded_file = params[:job][:package_picture].path
          cloudnary_file = Cloudinary::Uploader.upload(uploaded_file)
          #store this public_id value to the database
          #cloudnary_file['public_id']
          @job.package_picture = cloudnary_file['secure_url']
        end
    flash[:alert] = "Congratulation job #{@job.title.capitalize} has been successfully created and added to your profile"
    @job.save
    redirect_to root_path

    # respond_to do |format|
    #   if @job.save
    #     format.html { redirect_to @job, notice: 'Job was successfully created.' }
    #     format.json { render :show, status: :created, location: @job }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @job.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])
    if @job.accepted == false
      Job.where(:id => @job).update_all(:acceptor_id => current_user.id)
      Job.where(:id => @job).update_all(:accepted => true)
      flash[:alert] = "Congratulation job #{@job.title.capitalize} has been successfully accepted and added to your profile"
    elsif @job.accepted == true
      Job.where(:id => @job).update_all(:completed => true)
      flash[:alert] = "Congratulation job #{@job.title.capitalize} has been successfully marked completed and updated on your profile"
    end
    redirect_to root_path
    # respond_to do |format|
    #   if @job.update(job_params)
    #     format.html { redirect_to @job, notice: 'Job was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @job }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @job.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def map
    gon.jobs = Job.all
    @jobs = Job.where.not(:user_id => current_user.id).where(:accepted => false)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :package_picture, :start_location, :end_location, :date_pickup, :date_delivery, :accepted, :completed, :user_id, :acceptor_id, :start_lat, :start_long, :end_lat, :end_long)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_editform.html.erb
<%#<%= form_with(model: job, local: true) do |form| %>
<%= form_with scope: :job, model: @job, local: true do |form| %>

  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :start_location %>
    <%= form.text_field :start_location %>
  </div>

  <div class="field">
    <%= form.label :end_location %>
    <%= form.text_field :end_location %>
  </div>

  <div class="field">
    <%= form.label :date_pickup %>
    <%= form.datetime_select :date_pickup %>
  </div>

  <div class="field">
    <%= form.label :date_delivery %>
    <%= form.datetime_select :date_delivery %>
  </div>

  <div class="field">
    <%= form.hidden_field :acceptor_id, :value => nil %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/_form.html.erb
<%= form_with scope: :job, url: jobs_path, local: true do |form| %>

<% if job.errors.any? %>
<div id="error_explanation">
	<h2"><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

	<ul>
		<% job.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="card"></div>
<div class="card shadow p-3 mb-5 bg-white rounded text-light d-flex" id="create-form">
	<h3 class="default-text py-3"><i class="m-3 fas fa-shuttle-van"></i> New Job Posting</h3>
	<div class="form-group mx-5">
  <div class="d-inline-block">
  		<i class="fas fa-file-alt mr-2"></i>
		<label for="defaultForm-email" class="mr-2">Job Title</label>
  </div>
  		<%= form.text_field :title, class: "d-block" %>

	</div>
  <br>
	<div class="form-group mx-5">
    <div class="d-inline-block">

		<i class="fas fa-box mr-2"></i>
		<label for="defaultForm-email" class="mr-2">Package Image</label>
      </div>

		<%= form.file_field :package_picture, class: "d-block"  %>
	</div>
  <br>
	<div class="form-group mx-5">
      <div class="d-inline-block">

		<i class="fas fa-map-marker-alt mr-2"></i>
		<label for="defaultForm-email" class="mr-2">Start Location</label>
    </div>
		<%= form.text_field :start_location, class: 'autocomplete d-block' %>
	</div>
  <br>
	<div class="form-group mx-5">
        <div class="d-inline-block">

		<i class="fas fa-map-marker-alt"></i>
		<label for="defaultForm-email" class="mr-2">End Location</label>
    </div>
		<%= form.text_field :end_location, class:'autocomplete d-block' %>
	</div>
  <br>
	<div class="form-group mx-5">
          <div class="d-inline-block">

		<i class="fas fa-calendar-alt"></i>
		<label for="defaultForm-email" class="mr-2">Pickup Date</label>
        </div>

		<%= form.datetime_select :date_pickup, class: "d-block" %>
	</div>
  <br>
	<div class="form-group mx-5">
          <div class="d-inline-block">

		<i class="fas fa-calendar-alt"></i>
		<label for="defaultForm-email" class="mr-2">Delivery Date</label>
        </div>

		<%= form.datetime_select :date_delivery, class: "d-block" %>
	</div>
  <br>
	<div class="form-group mx-5">
		<%= form.submit "Create Job", class:"btn btn-default" %>
	</div>
  <br>
</div>

<div class="field">
	<%= form.hidden_field :start_lat, :value => nil %>
</div>

<div class="field">
	<%= form.hidden_field :start_long, :value => nil %>
</div>

<div class="field">
	<%= form.hidden_field :end_lat, :value => nil %>
</div>

<div class="field">
	<%= form.hidden_field :end_long, :value => nil %>
</div>

<div class="field">
	<%= form.hidden_field :acceptor_id, :value => nil %>
</div>

<div class="field">
	<%= form.hidden_field :accepted, :value => false %>
</div>

<div class="field">
	<%= form.hidden_field :completed, :value => false %>
</div>

<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=' + 'AIzaSyC-tEAh56qJBnYr7WTsvWyPqa1G9lRPpCc' + '&libraries=places&callback=initAutocomplete', 'data-turbolinks-track': 'reload'%>
<% end %>

<%= render 'editform', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>
    <%# <script type="text/javascript" src="/loggedinnav.js"></script> %>

<script>     
if (Cookies.get('nav') == undefined) {
    $('#mainNav').addClass('transs');
} else {
    $('.navbar-brand').removeClass('tranzz');
    $('#mainNav').removeClass('transs');
    $('#mainNav').addClass('navbar-shrink');
    $('#mainNav').addClass('noblocking');

}
</script>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Job title</th>
      <th>Start location</th>
      <th>End location</th>
      <th>Date pickup</th>
      <th>Date delivery</th>
      <th>Accepted</th>
      <th>Completed</th>
      <th>Created by User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.start_location %></td>
        <td><%= job.end_location %></td>
        <td><%= job.date_pickup %></td>
        <td><%= job.date_delivery %></td>
        <td><%= job.accepted %></td>
        <td><%= job.completed %></td>
        <td><%= job.user.username %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>
<%= link_to 'Home', root_path %>

    <script>     
if (Cookies.get('nav') == undefined) {
    $('#mainNav').addClass('transs');
} else {
    $('.navbar-brand').removeClass('tranzz');
    $('#mainNav').removeClass('transs');
    $('#mainNav').addClass('navbar-shrink');
    $('#mainNav').addClass('noblocking');

}
</script>

app/views/jobs/map.html.erb
<% provide :head_tags do %>
<%# Gon gem transfers rails hash data to JS %>
<%= include_gon %>
<%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyD_df4-HImzTZoMVtCQVkin0dXyPOYF7Y4
&libraries=places&callback=initMap', 'data-turbolinks-track': 'reload'%>
<% end %>
  <div class="container p-3 my-5 bg-white rounded border border-secondary text-center" style="box-shadow: 3px 3px 10px grey;">
  	<h4 class="text-info" style="color: black!important;">Find jobs within 2.0km of you</h4>
    <input type="text" class="form-control w-25 d-inline autocomplete" placeholder="I'm currently at..." id="job_start_location">
    <input type="text" class="form-control w-25 d-inline autocomplete" placeholder="I am going to..." id="job_end_location">
    <button class="btn btn-primary" style="color: black;" id="maptrigger">Show Jobs</button>
  </div>
<div class="wrapper shadow mb-5 ml-3 mr-3 bg-white rounded border border-secondary w-90">
	<div class="job-list" id='job-list' style="box-shadow: 3px 3px 10px grey; overflow: auto; ">
		<% @jobs.order('date_delivery asc').each do |job| %>
		<% p job %>
		<%= content_tag :div,
		class: "card text-left job-card",
			startloc: job.start_location,
			endloc: job.end_location,
			startlat: job.start_lat,
			startlong: job.start_long,
			endlat: job.end_lat,
			endlong: job.end_long do -%>
			<div class="card-body d-flex m-2">
				<div>
					<% if job.package_picture == nil %>
					<%= image_tag 'http://catawbabrewing.com/wp-content/themes/catawba/images/placeholder.png', height: 150, width: 150 %>
					<% else %>
					<%= image_tag job.package_picture, height: 150, width: 150 %>
					<% end %>
				</div>
				<div class="m-2">
					<h5 class="card-title" style="color: black;">
						<%= job.title.capitalize %>
					</h5>
					<p>
						<strong>Deliver from</strong> <%= job.start_location %> <strong>to</strong> <%= job.end_location %>
						<br>
						<strong>Pickup by</strong> <%= job.date_pickup.to_formatted_s(:long_ordinal) %> and <strong>deliver by </strong><%= job.date_delivery.to_formatted_s(:long_ordinal) %>
					</p>
					<a href="/users/<%= job.user.id %>" class="btn btn-primary mr-2"  style="color: black;" >Creator: <%= job.user.username %></a>
					<%= link_to 'Accept Job', job_path(job.id), method: :put, class:"btn btn-primary", style: "color: black;" %>
				</div>
			</div>
			<% end %>
			<% end %>
		</div>
		<div class="map-wrapper" id="map-wrapper">
			<div id="map"></div>
		</div>
	</div>
    <%# <script type="text/javascript" src="/loggedinnav.js"></script> %>
    <script>     
if (Cookies.get('nav') == undefined) {
    $('#mainNav').addClass('transs');
} else {
    $('.navbar-brand').removeClass('tranzz');
    $('#mainNav').removeClass('transs');
    $('#mainNav').addClass('navbar-shrink');
    $('#mainNav').addClass('noblocking');

}
</script>

app/views/jobs/new.html.erb
<% provide :head_tags do %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key=AIzaSyC-tEAh56qJBnYr7WTsvWyPqa1G9lRPpCc&libraries=places&callback=initJobForm', 'data-turbolinks-track': 'reload'%>
<% end %>

<%= render 'form', job: @job %>
    <script>     
if (Cookies.get('nav') == undefined) {
    $('#mainNav').addClass('transs');
} else {
    $('.navbar-brand').removeClass('tranzz');
    $('#mainNav').removeClass('transs');
    $('#mainNav').addClass('navbar-shrink');
    $('#mainNav').addClass('noblocking');

}
</script>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Start location:</strong>
  <%= @job.start_location %>
</p>

<p>
  <strong>End location:</strong>
  <%= @job.end_location %>
</p>

<p>
  <strong>Date pickup:</strong>
  <%= @job.date_pickup %>
</p>

<p>
  <strong>Date delivery:</strong>
  <%= @job.date_delivery %>
</p>

<p>
  <strong>Created by user:</strong>
  <%= @job.user.username %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', root_path %>

    <script>     
if (Cookies.get('nav') == undefined) {
    $('#mainNav').addClass('transs');
} else {
    $('.navbar-brand').removeClass('tranzz');
    $('#mainNav').removeClass('transs');
    $('#mainNav').addClass('navbar-shrink');
    $('#mainNav').addClass('noblocking');

}
</script>